// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: check.proto

package checker

import (
	"context"

	"bookstore/rpc/check/check"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckReq = check.CheckReq
	Response = check.Response

	Checker interface {
		Check(ctx context.Context, in *CheckReq, opts ...grpc.CallOption) (*Response, error)
	}

	defaultChecker struct {
		cli zrpc.Client
	}
)

func NewChecker(cli zrpc.Client) Checker {
	return &defaultChecker{
		cli: cli,
	}
}

func (m *defaultChecker) Check(ctx context.Context, in *CheckReq, opts ...grpc.CallOption) (*Response, error) {
	client := check.NewCheckerClient(m.cli.Conn())
	return client.Check(ctx, in, opts...)
}
